root: true

env:
  browser: true
  node: true
  es6: true

plugins:
  - solid

parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - eslint:recommended
  - plugin:solid/recommended

rules:
  no-unused-vars: 'warn'
